### ISSUE TITLE
Unity发布webgl在Chrome中运行报错

### ISSUE THREAD

**Issue by mxlhy** [zombieyang/puerts_unity_webgl_demo#1]
开发环境：Unity2020.3.9f1, window10
发布平台：webgl
运行环境：window10, Chrome[v90]

使用的是puerts_unity_webgl_demo直接打包测试，打包设置如下图：
![图片](https://user-images.githubusercontent.com/82790811/119455504-3ea43a80-bd6c-11eb-8bf2-f6bc3e41b365.png)
![图片](https://user-images.githubusercontent.com/82790811/119455574-4e238380-bd6c-11eb-8f7d-ca67c9f92da7.png)

在Chrome中运行报错，报错信息：Uncaught ReferenceError: unityInstance is not defined
![图片](https://user-images.githubusercontent.com/82790811/119455905-ace8fd00-bd6c-11eb-86ca-1ce2eb3d0b3d.png)

请问是我哪里操作出错？还是需要设置什么？

**Comment by zombieyang** [comment]
@ctxdegithub 已经修复
