### ISSUE TITLE
是不是需要在哪require一下puerts-runtime.js

### ISSUE THREAD

**Issue by zgz682000** [zombieyang/puerts_unity_webgl_demo#13]
运行小游戏报这个错：
VM2023 WAGame.js:2 TypeError: Cannot read property 'Init' of undefined
![image](https://user-images.githubusercontent.com/9474727/151507409-63d0cd25-6fde-4fb4-afb0-47534fde7fec.png)
貌似puerts-runtime.js没有运行
断点了一下发现下图第一个断点走了，第二个断点没走，也是貌似需要require一下的感觉
![image](https://user-images.githubusercontent.com/9474727/151507531-bdb0606c-6a4e-474c-80ef-631adf26a0ab.png)

**Comment by zombieyang** [comment]
对的，打成小游戏之后要在入口js那里先require一下
