### ISSUE TITLE
ts代码跑起来了，但游戏变得超卡。不知道跟这个报错有木有关系

### ISSUE THREAD

**Issue by zgz682000** [zombieyang/puerts_unity_webgl_demo#14]
plugin.js:188 An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it.
![image](https://user-images.githubusercontent.com/9474727/153565192-dfa1de59-51c3-4c92-ad12-455d3cb840f4.png)

**Comment by zgz682000** [comment]
而且在很多Android设备上会报这个错
![image](https://user-images.githubusercontent.com/9474727/153565445-bacf3007-72b1-4bc5-a220-bb7c7022b9a3.png)
IOS设备上能运行起来，但也超卡

**Comment by zgz682000** [comment]
> 而且在很多Android设备上会报这个错 ![image](https://user-images.githubusercontent.com/9474727/153565445-bacf3007-72b1-4bc5-a220-bb7c7022b9a3.png) IOS设备上能运行起来，但也超卡

跟到这个报错的原因了
<ReferenceError: WeakRef is not defined>
应该是这里报的
![image](https://user-images.githubusercontent.com/9474727/153584821-4035277c-949e-480b-8542-43b7b394c63f.png)

**Comment by zgz682000** [comment]
是不是Android真机环境下不支持WeakRef啊

**Comment by zgz682000** [comment]
大佬，es2021新特性啊这都是

**Comment by zgz682000** [comment]
> plugin.js:188 An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it. ![image](https://user-images.githubusercontent.com/9474727/153565192-dfa1de59-51c3-4c92-ad12-455d3cb840f4.png)

巨卡的问题发现原因了，webgl不能设置targetFrame，一设置就变卡顿

**Comment by zgz682000** [comment]
现在就剩es2021新特性的问题了大佬，orz

**Comment by zombieyang** [comment]
你在群里加下我QQ，这个事情在和微信一起处理
