### ISSUE TITLE
篮球Demo发布WebGL版本后构建js资源报错

### ISSUE THREAD

**Issue by Sedimentation** [zombieyang/puerts_unity_webgl_demo#15]
发布WebGL版本后，根据Log提示使用puerts-webgl/build js工具构建js资源时报错，初步定位到WebGLPostProcessor.cs中定义的postProcess回调为空

已构建TS工程puerts-webgl，修改过tsconfig.json中typeRoots中的路径
已安装mkdirp

'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jslib-src@1.0.0 build: `cd PuertsDLLMock && tsc -p tsconfig.json && webpack -c webpack.config.js && rm -rf output`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jslib-src@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-02-17T02_45_29_102Z-debug.log

UnityEngine.Debug:LogError (object)
PuertsStaticWrap.UnityEngine_Debug_Wrap:F_LogError (intptr,intptr,intptr,int,long) (at Assets/Gen/UnityEngine_Debug_Wrap.cs:635)
Puerts.PuertsDLL:EvalChecked (intptr,string,string) (at Assets/ThirdParty/Puerts/Src/PuertsDLL.cs:231)
Puerts.JsEnv:Eval<System.Action`1<string>> (string,string) (at Assets/ThirdParty/Puerts/Src/JsEnv.cs:278)
WebGLPuertsPostProcessor:run (string,string) (at Assets/Source/Editor/WebGLPostProcessor.cs:31)
WebGLPuertsPostProcessor:minigame () (at Assets/Source/Editor/WebGLPostProcessor.cs:63)

![Q$}}KQOE59 5$E4Y5XRH5_R](https://user-images.githubusercontent.com/99854462/154396276-1d5eec58-455f-401c-8004-53853a587015.png)
![} QZDT92TZMAR7SND}`~1@M](https://user-images.githubusercontent.com/99854462/154396287-168829c1-6125-4db0-8445-4b263c6d6929.png)
![N$%0}71GJM@TV~ ML(7XD%N](https://user-images.githubusercontent.com/99854462/154396315-05327e49-4c45-4696-8815-25df7a94e898.png)

**Comment by zombieyang** [comment]
从报错信息上看，应该是windows没有`rm`命令导致的

**Comment by zombieyang** [comment]
改用了`rimraf`你再试试1a4720e

**Comment by Sedimentation** [comment]
> 从报错信息上看，应该是windows没有`rm`命令导致的

好的，谢谢大佬指导
都忘了写环境了，Windows10，Unity2019.4.24f1

**Comment by zombieyang** [comment]
也就大windows会出现npm输出乱码的问题

**Comment by Sedimentation** [comment]
> 

好的，经过以下测试，又遇到一个问题需要解决，空了麻烦大佬看下。

1、更新package.json后，重新编译，报rimraf命令错误，通过npm install rimraf -g解决。
2、重新编译，WebGLPostProcessor.cs中39行代码的“mv”命令报错，修改为“move”解决。
然后就报这个错了，有点蒙。

ϵͳ�Ҳ���ָ����·����

UnityEngine.Debug:LogError (object)
PuertsStaticWrap.UnityEngine_Debug_Wrap:F_LogError (intptr,intptr,intptr,int,long) (at Assets/Gen/UnityEngine_Debug_Wrap.cs:635)
Puerts.PuertsDLL:EvalChecked (intptr,string,string) (at Assets/ThirdParty/Puerts/Src/PuertsDLL.cs:231)
Puerts.JsEnv:Eval<System.Action`1<string>> (string,string) (at Assets/ThirdParty/Puerts/Src/JsEnv.cs:278)
WebGLPuertsPostProcessor:run (string,string) (at Assets/Source/Editor/WebGLPostProcessor.cs:31)
WebGLPuertsPostProcessor:minigame () (at Assets/Source/Editor/WebGLPostProcessor.cs:63)

![无标题](https://user-images.githubusercontent.com/99854462/154421481-e16da322-79a5-42be-bf3c-f788f7bd0f5d.jpg)

**Comment by Sedimentation** [comment]
40行cwd修改为cd，修复ϵͳ�Ҳ���ָ����·����问题，再次构建js资源，报package.json找不到，路径为Unity工程根目录/package.json，应该为Unity工程根目录/puerts-webgl/package.json，目前在找路径定义……

**Comment by zombieyang** [comment]
你不reopen issue我收不到提示的。。

**Comment by Sedimentation** [comment]
> 你不reopen issue我收不到提示的。。

之前没找到reopen issue，见谅见谅
接package.json找不到的问题，补一张Unity Console图
![image](https://user-images.githubusercontent.com/99854462/163089119-47f1cf81-b4ad-4990-96d6-c6493957ab83.png)

**Comment by Sedimentation** [comment]
感谢大佬修复，刚试了下，拉取最新的修改直接发布版本，依然报XLua的错误。
移除XLua并屏蔽相关代码，能正确发布出WebGL，不过在“build puerts-ts for brower”时报错TypeError: build is not a function
    at chunk:10:21
![image](https://user-images.githubusercontent.com/99854462/163904863-898df633-ad30-49fc-9152-f4a7d9bde614.png)

**Comment by zombieyang** [comment]
我自己测了也发现还没弄好。我干脆顺便合一下master再修复好了，你现在的进度还方便大幅更新Puerts不？（主要是有没有做大量魔改）

**Comment by Sedimentation** [comment]
没关系，大佬放心改好了，目前我还处于学习评估阶段呢，哈哈

**Comment by zombieyang** [comment]
已经合并puerts1.3.3。

**Comment by Sedimentation** [comment]
收到，我去试试，感谢

**Comment by Sedimentation** [comment]
刚测试了v1.3.3版本WebGL篮球Demo
Windows下可以正确发布、部署了
感谢

需要注意一下3点
1、编译报错PuerTS.WebGL未定义，Assets\Source\BasketballDemo\BaseClass\JsMonoBehaviour.cs(18,19): error CS0234: The type or namespace name 'WebGL' does not exist in the namespace 'Puerts' (are you missing an assembly reference?)
定义写在UNITY_WEBGL宏中，将项目切换至WebGL平台解决。（平台兼容性）

2、运行时为默认场景，没有加载出篮球Demo场景，需要添加篮球Demo场景到BuildScene。（项目发布配置）

3、build puerts-js for browser过程比较长，没有提示，我以为CMD窗口关闭后就完成了，并部署到服务器，但这时puerts_browser_js_resources.js还没生成，后面再上传puerts_browser_js_resources.js也一样报错puerts-runtime.js加载不了，猜测是缓存导致，清理浏览器缓存后正确运行。（打包过程提示及缓存自动清理）

缓存导致puerts-runtime.js加载不了的报错：
exception thrown: Error: cannot found PuertsWebGL script. please find some way to load puerts-runtime.js,Error: cannot found PuertsWebGL script. please find some way to load puerts-runtime.js
    at _InitPuertsWebGL

Uncaught Error: cannot found PuertsWebGL script. please find some way to load puerts-runtime.js
    at _InitPuertsWebGL (b9d542d6-dfcb-4381-a5c0-813f90518ef9:8)
