### ISSUE TITLE
[1.1.x分支] 导出的puerts_browser_js_resources内容为空

### ISSUE THREAD

**Issue by mi1890** [zombieyang/puerts_unity_webgl_demo#28]
## how to reproduce | 复现步骤

![image](https://user-images.githubusercontent.com/5334863/206506564-950b922c-ecf3-4580-ac2d-77ae9e81f43c.png)
![image](https://user-images.githubusercontent.com/5334863/206506692-d2397165-e32f-4112-8f72-2bfd6bd78db3.png)

**Comment by zombieyang** [comment]
1.1.x分支还木有做完……

**Comment by zombieyang** [comment]
做完我会发一个release以及打tag的
