### ISSUE TITLE
使用webgl转换微信小游戏，ILoader类没有生效

### ISSUE THREAD

**Issue by platefacer** [zombieyang/puerts_unity_webgl_demo#29]
如何让自定义的Loader,小游戏中生效

        jsEnv = Puerts.WebGL.GetBrowserEnv(new JsLoader());

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts_unity_webgl_demo/blob/master/package/Editor/WebGLPostProcessor.cs#L9
根据这段注释操作试试。
1.1分支上有其它更具体的示例

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts_unity_webgl_demo/wiki/%E6%95%99%E5%AD%A6%E6%AD%A5%E9%AA%A4%E4%B8%AD%EF%BC%8C%60%E6%9E%84%E5%BB%BA%60%E5%AE%9E%E9%99%85%E5%81%9A%E4%BA%86%E4%BB%80%E4%B9%88%EF%BC%9F
