### ISSUE TITLE
在ts端注册 Action类的函数,  没有收到回调

### ISSUE THREAD

**Issue by Xiangdu1234** [zombieyang/puerts_unity_webgl_demo#32]
在微信小游戏环境下:
在ts端注册 Action类的函数,  没有收到回调
但是注册的 Delegate类可以正常收到回调.

c# 接口:
class: MessageManager.
public static MessageDelegate tsDelegate;
public static Action<string, string, string> tsLogAction;

ts:示例
GameUtils.MessageManager.tsLogAction = NativeBridge.onCsLogsBack;
GameUtils.MessageManager.tsDelegate = new  GameUtils.MessageDelegate(this.onNativeCallBack.bind(this.instance) );	 

同样是一个类的2个回调函数,
tsDelegate->onNativeCallBack 可以正常执行回调. 但是tsLogAction->onCsLogsBack 收不到回调.

**Comment by Xiangdu1234** [comment]
环境:
puerts 版本 1.4.0; unity 2021.2.5
puerts_webgl: 最新版

**Comment by Xiangdu1234** [comment]
环境:
puerts 版本 1.4.0; unity 2021.2.5
puerts_webgl: 最新版

**Comment by zombieyang** [comment]
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/blob/main/Design/UnityVersion.md
这个版本的Unity亲测有问题。待与Unity中国沟通

**Comment by zombieyang** [comment]
无法稳定复现

**Comment by zombieyang** [comment]
官方版Unity使用2021.2.11以上版本
中国特供版Unity使用2021.2.5 c302及以上版本
