### ISSUE TITLE
[unity] Mac OS下npm等命令执行失败

### ISSUE THREAD

**Issue by bydreamxxx** [zombieyang/puerts_unity_webgl_demo#34]
## error log | 日志或报错信息
npm i 报错 unity的Mac下没有继承系统环境变量
手动在Javascripts~下执行后
报npx: command not found
再次手动执行后，只生成了puerts-runtime.js

## context | 编译/运行环境
unity 2021.3.5f1c1
MacOS Monterey 12.6.1
## how to reproduce | 复现步骤
1.执行build puerts-js for brower

**Comment by bydreamxxx** [comment]
通过设置execSync的
env: {PATH: "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"}
可以成功在Mac下生成
// webpack
    execSync('npx webpack -c webpack.config.js', { 
        cwd: path.join(__dirname, 'PuertsDLLMock'),env: {PATH: "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"}
    })
npm i那个也一样，设置环境变量后可以正常

**Comment by zombieyang** [comment]
新版去掉了这个进程调用
