### ISSUE TITLE
[unity] 感觉最新版本有很多莫名其妙的报错

### ISSUE THREAD

**Issue by Halliwood** [zombieyang/puerts_unity_webgl_demo#39]
## error log | 日志或报错信息

之前用的PuerTS_V8_1.4.0-rc.6和webgl1.0.0-rc.2，不管是网页版还是导出小游戏都很正常，这两天升级到com.tencent.puerts.core@2.0.0-pre.2和com.tencent.puerts.webgl@1.1.1-pre.1，除了本地Editor运行正常，不管是网页版还是小游戏都会出现各种随机的报错，刷新页面有时候就没报错了，有时候就换个其他的报错~~

比如一会会报各种莫名其妙的csharp获取的对象是null
比如`csharp.mjs`中，一会`name`会报错`TypeError: Cannot convert a Symbol value to a string`
```
function createTypeProxy(namespace) {
    return new Proxy(new Namespace, {
        get: function(cache, name) {
            if (!(name in cache)) {
                let fullName = namespace ? (namespace + '.' + name) : name;
                if (/\$\d+$/.test(name)) {
                    let genericTypeInfo = cache[name] = new Map();
                    genericTypeInfo.set('$name', fullName.replace('$', '`'));

                } else {
                    let cls = csTypeToClass(fullName);
                    if (cls) {
                        cache[name] = cls;
                    } else {
                        cache[name] = createTypeProxy(fullName);
                        //console.log(fullName + ' is a namespace');
                    }
                }
            }
            return cache[name];
        }
    });
}
```

## how to reproduce | 复现步骤
说不上来，就是很随机

## more | 其他
另外webgl依赖的com.tencent.puerts.core@2.0.0-pre.2这个版本本身在https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/changelog-hans.md
上就没有，是不是本身就不稳定

**Comment by zombieyang** [comment]
求稳就不着急升，都是preview版本。

能否给一个比较高概率复现的demo给我

**Comment by Halliwood** [comment]
> 求稳就不着急升，都是preview版本。
> 
> 能否给一个比较高概率复现的demo给我

不好意思，不知道具体是哪里的问题，可复现的demo整不出来。。只是感觉可能是指针错位了，每次刷新页面报错都不一样，有时候是log出现乱码，如
![image](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/860632/39f638d5-4eb7-4b8f-9d3c-75b9153bcfce)
目前看字符串有问题的概率比较高，比如下述代码：
![image](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/860632/71b5c4ae-7d04-49e3-8c10-dae7f8216588)
按理path应该变成path.ab，但有时候不会：
![image](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/860632/3f0ef99d-bfb8-42c1-a89b-b1eb209f4a39)

**Comment by zombieyang** [comment]
类似问题：https://github.com/Tencent/puerts/issues/1401

已提交修复，有空也帮忙验证下

**Comment by Halliwood** [comment]
> 类似问题：[Tencent/puerts#1401](https://github.com/Tencent/puerts/issues/1401)
> 
> 已提交修复，有空也帮忙验证下

新版本没这个问题了
