### ISSUE TITLE
[unity] 微信小游戏报错

### ISSUE THREAD

**Issue by Halliwood** [zombieyang/puerts_unity_webgl_demo#41]
## error log | 日志或报错信息
微信小游戏会分包game.js会被执行，导致报错
开发者工具报错：
![image](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/860632/fca64da8-5f8e-4f47-9aa0-eb8db3e550d3)

真机报错：
![image](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/860632/c016ac6d-8ae3-41bc-8b62-ed20fd77f35a)

猜测是因为这里的原因
![image](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/860632/8c751e50-ed23-4134-934b-ee98074acb60)

## context | 编译/运行环境
PuerTS_V8_2.0.0-rc.1 + com.tencent.puerts.webgl@2.0.0-rc.1 + puerts-commonjs-upm-1.1.0-pre.0

## how to reproduce | 复现步骤
1.
2.
3.

## more | 其他
虽然这个报错没什么实际影响，游戏还是可以玩
但之前用的PuerTS_V8_1.4.0-rc.6和webgl@1.0.0-rc.2没有这个问题

**Comment by zombieyang** [comment]
微信小游戏一直不支持eval，之前的版本不可能没问题。

**Comment by Halliwood** [comment]
> 微信小游戏一直不支持eval，之前的版本不可能没问题。

我把插件回退了确实就没这个报错了，后来打断点看了，两个插件版本的分歧在这块。不过这个报错不影响游戏正常跑，先不管了吧。
