### ISSUE TITLE
[unity] description

### ISSUE THREAD

**Issue by kefeibuhuifei** [zombieyang/puerts_unity_webgl_demo#42]
![e1c81aa5bcb7e2cd019d4dac44b291d](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/33917095/aea6ee50-dba4-413a-bb1c-8d49442cb7ef)

## error log | 日志或报错信息
Cannot perform upm operation: Unable to add package [https://github.com/zombieyang/puerts_unity_webgl_demo.git?path=/package]:
  Cannot checkout repository [https://github.com/zombieyang/puerts_unity_webgl_demo.git] on target path [package]:
    Error when executing git command. error: pathspec 'package' did not match any file(s) known to git
 [NotFound]

## context | 编译/运行环境
Unity2019.4.40
## how to reproduce | 复现步骤
1.
![e1c81aa5bcb7e2cd019d4dac44b291d](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/33917095/6c7dc44d-add2-4d29-9be9-a7bddbd0693e)
按照步骤安装puerts,已成功
2.再upm里面 https://github.com/zombieyang/puerts unity webgl demogit?path=/package
3.就会出现报错

**Comment by zombieyang** [comment]
已经更新readme了。感谢反馈
