### ISSUE TITLE
[unity] TypeError: CS.Puerts.PathHelper.IsRelative is not a function

### ISSUE THREAD

**Issue by Yiiip** [zombieyang/puerts_unity_webgl_demo#61]
## error log | 日志或报错信息
`TypeError: CS.Puerts.PathHelper.IsRelative is not a function`
如图：
![Picture](https://github.com/zombieyang/puerts_unity_webgl_demo/assets/10251493/d156148a-afd1-46c1-beaf-96a07b736a46)

## context | 编译/运行环境
Unity WebGL
PuerTS WebGL 2.0.5

## how to reproduce | 复现步骤
```csharp
Action action = jsEnv.ExecuteModule("lypTestJS.mjs").Get<Action>("testSort");
action?.Invoke();
```

本地还改了`puerts_unity_webgl_demo\packages\webgl-jsbuild\upm\Editor\WebGLPostProcessor.cs`
```csharp
public class WebGLPuertsPostProcessor {

    public static List<string> fileGlobbers = new List<string> 
    {
        Path.GetFullPath("Packages/com.tencent.puerts.core/") + "/**/Resources/**/*.mjs",
        Path.GetFullPath("Packages/com.tencent.puerts.commonjs/") + "/**/Resources/**/*.mjs",
        Application.dataPath + "/**/Resources/**/*.mjs",
        Application.dataPath + "/**/Resources/**/*.cjs",
    };

    ......
}
```

在UnityEditor中正常运行，打包到WebBrowser中报了错

**Comment by zombieyang** [comment]
https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Runtime/Src/PathHelper.cs#L17
给这个函数加个Preserve防裁剪试试

**Comment by Yiiip** [comment]
> https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Runtime/Src/PathHelper.cs#L17 给这个函数加个[Preserve]防裁剪试试

试了下有效果，除了`IsRelative`外，PathHelper里其他的静态函数也要加上`[UnityEngine.Scripting.Preserve]`
