### ISSUE TITLE
1.42版本  unity版本 2022.3.34f1c1 上发布webgl打开后报错 调用Puerts.WebGL.GetBrowserEnv( 报错： ReferenceError: _memset is not defined     at _InitPuertsWebGL (Build.framework.js:2340:24)

### ISSUE THREAD

**Issue by kefeibuhuifei** [zombieyang/puerts_unity_webgl_demo#63]
## error log | 日志或报错信息
 ReferenceError: _memset is not defined     at _InitPuertsWebGL (Build.framework.js:2340:24)
![image](https://github.com/user-attachments/assets/c585d369-86a2-475a-8165-bf9c0226f904)

## context | 编译/运行环境
2023.3.34F1CA   window11

## how to reproduce | 复现步骤
1.  按照流程安装 puerts1.42  与puerts webgl版本
2. 按正常发布流程
3. 浏览器打开发布好的工程，调用接口 Puerts.WebGL.GetBrowserEnv 就会出现

**Comment by Halliwood** [comment]
这个把_memset导出就好了
PlayerSettings.WebGL.emscriptenArgs += "-s \"EXPORTED_FUNCTIONS=['_main', '_memset']\"";

**Comment by zombieyang** [comment]
1.4.2没精力管了，按楼上的做法改吧

**Comment by kefeibuhuifei** [comment]
> 这个把_memset导出就好了 PlayerSettings.WebGL.emscriptenArgs += "-s "EXPORTED_FUNCTIONS=['_main', '_memset']"";

thanks
