### ISSUE TITLE
[unity] Error: cannot found PuertsWebGL script. please find some way to load puerts-runtime.js

### ISSUE THREAD

**Issue by mrwhalett** [zombieyang/puerts_unity_webgl_demo#71]
## error log | 日志或报错信息
Error: cannot found PuertsWebGL script. please find some way to load puerts-runtime.js
t _InitPuertsWebGL (http://127.0.0.1:8081/Build/assets.framework.js:1483:9)
    at MainEnv_Get_mAC2BF76F4EABB1D291F740413E6F3E92ABC9A8AA (http://127.0.0.1:8081/Build/assets.wasm:wasm-function[143263]:0x26ccc6f)
    at TsManager_CreateJsEnv_mB56B793F485BE69AF85870154B1D2579D32B8453
## context | 编译/运行环境
Unity 2021.3.32f1
谷歌浏览器
Puerts 2.1.0
Puerts commonjs support 2.0.5
Puerts webgl js builder 2.0.5
Puerts webgl support 2.0.5
Puerts TS loader 2.0.5

## how to reproduce | 复现步骤
1.WebGL打包后网页运行

**Comment by zombieyang** [comment]
![Uploading image.png…]()

**Comment by mrwhalett** [comment]
![20241104134854](https://github.com/user-attachments/assets/2bffb227-297f-4874-a87d-3eb841c1cda2)
![22222](https://github.com/user-attachments/assets/380beb11-86a9-4a08-9bfe-218b24136ba4)
感谢回答，第四、五步分别如图报错

**Comment by zombieyang** [comment]
群里

> ![20241104134854](https://private-user-images.githubusercontent.com/15363918/382654022-2bffb227-297f-4874-a87d-3eb841c1cda2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDYyMDgsIm5iZiI6MTczMDcwNTkwOCwicGF0aCI6Ii8xNTM2MzkxOC8zODI2NTQwMjItMmJmZmIyMjctMjk3Zi00ODc0LWE4N2QtM2ViODQxYzFjZGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA3MzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZTE4YjU2ZjMzNDE4M2FkZGQ2YTViOWIzZTE0NDZjYTYxZmNkZTE1MjVkMTRiNzA4MGI5YjAxZmJmZjY1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fc9boSWkydxD73hoHITFFRCMD5wZRTIXs8_0Q9twqmI) ![22222](https://private-user-images.githubusercontent.com/15363918/382654028-380beb11-86a9-4a08-9bfe-218b24136ba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDYyMDgsIm5iZiI6MTczMDcwNTkwOCwicGF0aCI6Ii8xNTM2MzkxOC8zODI2NTQwMjgtMzgwYmViMTEtODZhOS00YTA4LTliZmUtMjE4YjI0MTM2YmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA3MzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNGQwMDZiZmI4Nzc2MDQwNDQ1ODE2NWQ3YzAwYjM1ZTc1OTlmYTViZDJjZGNmNTk3ODFkNTkyYmIzOTM2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q8uqTPD7PH3KVoOU9tSF18NhLCSKLS2V4SIZRdJjZBI) 感谢回答，第四、五步分别如图报错

群里跟你说过了，puerts本体要用node版。
